#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define X_PLANE_PORT 49000
#define X_PLANE_COMPUTER_IP   {192, 168, 12, 1}
#define X_PLANE_CONTROLLER_IP {192, 168, 12, 100}

#define WIFI_SSID "XPlaneNetwork"
#define WIFI_PASSWORD "xplane11net"

#define UPDATE_SEND_PERIOD 80

#define BUTTON_DEBOUNCE_TIME 30

#endif // DEFINITIONS_H