#ifndef PINS_H
#define PINS_H

#define BOOT_INTO_CALIBRATION_MODE_PIN GPIO_NUM_23

#define YOKE_ROLL_SENSOR_PIN GPIO_NUM_36
#define YOKE_PITCH_SENSOR_PIN GPIO_NUM_39

#define ENGINE_CONTROLS_MIXTURE_SENSOR_PIN GPIO_NUM_34
#define ENGINE_CONTROLS_THROTTLE_SENSOR_PIN GPIO_NUM_35

#endif // PINS_H