#ifndef PINS_H
#define PINS_H

#include <Arduino.h>

#define SPI_MOSI       GPIO_NUM_23
#define SPI_SCLK       GPIO_NUM_18
#define TFT_DISPLAY_CS GPIO_NUM_21
#define TFT_DISPLAY_DC GPIO_NUM_22

#define ELEVATOR_TRIM_PIN_1 GPIO_NUM_17
#define ELEVATOR_TRIM_PIN_2 GPIO_NUM_16

#define YOKE_ROLL_SENSOR_PIN  GPIO_NUM_36
#define YOKE_PITCH_SENSOR_PIN GPIO_NUM_39

#define COM_NAV_RADIO_DISPLAY_PIN_CS GPIO_NUM_5

#define COM_NAV_RADIO_COM_KHZ_ENCODER_PIN_1 GPIO_NUM_13
#define COM_NAV_RADIO_COM_KHZ_ENCODER_PIN_2 GPIO_NUM_12
#define COM_NAV_RADIO_COM_MHZ_ENCODER_PIN_1 GPIO_NUM_14
#define COM_NAV_RADIO_COM_MHZ_ENCODER_PIN_2 GPIO_NUM_27
#define COM_NAV_RADIO_NAV_KHZ_ENCODER_PIN_1 GPIO_NUM_26
#define COM_NAV_RADIO_NAV_KHZ_ENCODER_PIN_2 GPIO_NUM_25
#define COM_NAV_RADIO_NAV_MHZ_ENCODER_PIN_1 GPIO_NUM_33
#define COM_NAV_RADIO_NAV_MHZ_ENCODER_PIN_2 GPIO_NUM_32

#define ENGINE_CONTROLS_MIXTURE_SENSOR_PIN  GPIO_NUM_34
#define ENGINE_CONTROLS_THROTTLE_SENSOR_PIN GPIO_NUM_35

#define COM_NAV_RADIO_COM_FREQUENCY_TRANSFER_BUTTON_PIN GPIO_NUM_4
#define COM_NAV_RADIO_NAV_FREQUENCY_TRANSFER_BUTTON_PIN GPIO_NUM_15

#endif // PINS_H 
